/**
 * Ruler API
 * Ruler API is a flexible API for rules. Originally designed for FIRST Robotics Competition, it is flexible in nature to allow for any program to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import GetRuleApi from './api/GetRuleApi';
import GetRuleListApi from './api/GetRuleListApi';


/**
* Ruler_API_is_a_flexible_API_for_rules__Originally_designed_for_FIRST_Robotics_Competition_it_is_flexible_in_nature_to_allow_for_any_program_to_use_it_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RulerApi = require('index'); // See note below*.
* var xxxSvc = new RulerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RulerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RulerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RulerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
    * The GetRuleApi service constructor.
    * @property {module:api/GetRuleApi}
    */
    GetRuleApi,

    /**
    * The GetRuleListApi service constructor.
    * @property {module:api/GetRuleListApi}
    */
    GetRuleListApi
};
